version: '3'

services:
  application: 
    build: .
    ports:
      - "8000:8000"
    links: 
      - database
    depends_on:
      - database

    environment: 
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel_user
      DB_PASSWORD: 123456
    volumes:
      - ./:/app


  database:
    image: 'mysql:5.7'
    ports:
      - 13306:3306

    # the mysql image uses these to create database and users
    environment: 
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: '123456'
    volumes:
      - /var/www/html/data:/var/lib/mysql

