version: '3'

services:
  notification-service: 
    build: .
    ports:
      - "8001:80"
    links: 
      - notification-db
    depends_on:
      - notification-db

    # environment: 
      # DB_HOST: notification-db
      # DB_PORT: 3306
      # DB_DATABASE: laravel
      # DB_USERNAME: laravel_user
      # DB_PASSWORD: 123456
    # env_file:
    #   - .env
    command: "bash -c 'php artisan migrate && apachectl -DFOREGROUND'"


  notification-db:
    image: 'mysql:5.7'
    ports:
      - 23306:3306

    # the mysql image uses these to create database and users
    env_file:
      - mysql.env
    # environment: 
      # MYSQL_ROOT_PASSWORD: 'root'
      # MYSQL_DATABASE: laravel
      # MYSQL_USER: laravel_user
      # MYSQL_PASSWORD: '123456'
    volumes:
      - $HOME/notification-service/mysql-data:/var/lib/mysql

